<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="TYSS-Tatasky-7" name="com.news18.runner.RunCukesTest" tests="1" failures="0" timestamp="9 Dec 2021 12:52:51 GMT" time="1109.928" errors="1">
  <testcase name="feature" time="1109.928" classname="com.news18.runner.RunCukesTest">
    <error type="cucumber.runtime.CucumberException" message="java.lang.AssertionError: Got 2 mismatch">
      <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: Got 2 mismatch
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
	at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.AssertionError: Got 2 mismatch
	at org.testng.Assert.fail(Assert.java:94)
	at com.api.base.ApplicationFuncs.writeDataIntoExcel(ApplicationFuncs.java:216)
	at com.news18.stepdefinition.Stepdefinitions_English.compare_the_stories_of_Mobile_Web_and_Mobile_App(Stepdefinitions_English.java:115)
	at âœ½.Then Compare the stories of Mobile Web and Mobile App(features/A_News18_English.feature:11)
]]>
    </error>
  </testcase> <!-- feature -->
</testsuite> <!-- com.news18.runner.RunCukesTest -->
